name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore nuget packages
      run: nuget restore $Env:GITHUB_WORKSPACE\EETLauncher.sln
    - name: Build Release
      run: msbuild $Env:GITHUB_WORKSPACE\EETLauncher\EETLauncherMVVM.csproj /p:Configuration=Release
      
