name: CI

on: [push]

jobs:
  a1:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild
      run: msbuild -t:restore -p:Configuration=Release $Env:GITHUB_WORKSPACE\EETLauncher.sln
    - name: GCI
      run: Get-ChildItem $Env:GITHUB_WORKSPACE -Recurse
    

      #- name: Upload artifact
      #  uses: actions/upload-artifact@master
      #  with:
      #    name: EETLauncher-Release
      #    path: EETLauncher\bin\Release
