name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild
      run: msbuild -t:restore -p:Configuration=Release $Env:GITHUB_WORKSPACE\EETLauncher.sln
    - name: Display the path
      run: echo ${env:PATH}
      shell: pwsh
    - name: GCI
      run: Get-ChildItem $Env:GITHUB_WORKSPACE -Recurse
      shell: pwsh
      #- name: Upload artifact
      #  uses: actions/upload-artifact@master
      #  with:
      #    name: EETLauncher-Release
      #    path: EETLauncher\bin\Release
